name: Deploy API to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: europe-west4
      SERVICE_NAME: football-mlops-api
      REPO_NAME: football-mlops

      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps for DVC
        run: |
          pip install -r requirements.txt
          pip install "dvc[gs]"

      - name: Configure DVC remote (GCS)
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
          dvc remote modify --local gcsremote credentialpath gcp-key.json

      - name: Pull data, models & champion config
        run: |
          dvc config cache.type copy --local
          dvc pull

      - name: Debug list data and models
        run: |
          echo "PWD: $(pwd)"
          echo "---- data/processed ----"
          ls -R data/processed || echo "data/processed missing"
          echo "---- models ----"
          ls -R models || echo "models missing"
          echo "---- app/models ----"
          ls -R app/models || echo "app/models missing"

      - name: Auth to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build container image
        run: |
          IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$SERVICE_NAME:latest"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t "$IMAGE" .

      - name: Smoke test container in CI
        run: |
          docker run -d --name api -e PORT=8080 -p 8080:8080 "$IMAGE"
          echo "Waiting for container to boot..."
          sleep 25
          echo "Calling /docs..."
          set -x
          curl -f http://localhost:8080/docs || (
            echo "Container logs:"
            docker logs api
            exit 1
          )
          docker rm -f api

      - name: Push image
        run: docker push "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE" \
            --platform managed \
            --region "$REGION" \
            --allow-unauthenticated
